name: ztime
description: "An aviation toolkit with flight calculators, unit conversions, and time zone management."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

# To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2 # For state management (use latest version)
  shared_preferences: ^2.2.3 # For saving theme preference (use latest version)
  timezone: ^0.10.1
  flutter_timezone: ^4.1.0
  url_launcher: ^6.3.0

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: lib/assets/zTimeLogoWhiteBack.png
  min_sdk_android: 21 
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/assets/zTimeLogo.png"

